# Generated by Django 6.0.7 on 2026-07-14 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('merchant', models.CharField(max_length=255)),
                ('category', models.CharField(default='Other', max_length=100)),
                ('date', models.DateTimeField()),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('original_sms', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('sms', 'sms'), ('notification', 'notification'), ('csv', 'csv'), ('pdf', 'pdf')], default='manual', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imported_merchant', models.CharField(max_length=255)),
                ('imported_date', models.DateTimeField()),
                ('imported_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to=settings.AUTH_USER_MODEL)),
                ('sms_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=30000.0, max_digits=12)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salary_day', models.IntegerField(default=10)),
                ('auto_salary_enabled', models.BooleanField(default=True)),
                ('last_salary_applied', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
